CONVERSION = [
    'App Became Active',
    'Countdown Pro Button',
    'Deck Created',
    'Display Limit Modal',
    'Display Limit Notification',
    'Display Video Editor Modal',
    'Display Zuru Upgrade Modal',
    'Download PPTX',
    'Downloaded Video',
    'Editor Opened',
    'Ended Onboarding',
    'Export',
    'Export PPT',
    'Export PPTX',
    'Land on Classroom Page',
    'Land on Education Page',
    'Land on Homepage',
    'Land on Pricing Page',
    'Land on Realtor Page',
    'Land on Zuru Page',
    'Limit Button',
    'Limit Modal Edu Button',
    'Limit Modal Pro Button',
    'New Deck',
    'Privacy',
    'Recorded Audio',
    'Set Privacy Public',
    'Set Privacy Restricted',
    'Share',
    'Sign In',
    'Slide start',
    'Start',
    'Started Onboarding',
    'View player page',
    'Zuru Upgrade Edu Button',
    'Zuru Upgrade Pro Button',
    'signin',
]

CHURN = [
    "account_age",
    "camp_deliveries",
    "Slide start",
    "vertical_educator",
    "Editor Opened",
    "Deck Created",
    "vertical_marketing",
    "Started Onboarding",
    "Export",
    "signin",
    "App Became Active",
    "Sign In",
    "View player page",
    "Land on Pricing Page",
    "Share",
    "Ended Onboarding",
    "Display Video Editor Modal",
    "Export PPTX",
    "Recorded Audio",
    "Land on Classroom Page",
    "vertical_real_estate",
    "Export PPT",
    "vertical_student",
    "Display Limit Notification",
    "Land on Zuru Page",
    "Start",
    "Land on Education Page",
    "Set Privacy Restricted",
    "Display Welcome Countdown",
    "Privacy",
    "vertical_coach",
    "vertical_health",
    "vertical_non-profit",
    "vertical_religious_organization",
    "vertical_professional",
    "Land on Checkout Page",
    "Click Button",
    "Downloaded Video",
    "Successfully completed edu signup",
    "Set Privacy Public",
    "vertical_sales",
    "Validation failed",
    "signup",
    "New Deck",
    "vertical_small_business_owner",
    "upgrade",
    "vertical_other",
    "Download PPTX",
    "Successfully completed pro signup",
    "Display Limit Modal",
    "Error on payment",
    "Limit Button",
    "Sign Up",
    "Successfully completed classroom upgrade",
    "Successfully completed edu upgrade",
    "Successfully completed pro upgrade",
    "vertical_hr",
    "vertical_lawyer",
]
