CONVERSION = [
    'Land on Pricing Page',
    'Export',
    'Export PPT',
    'Export PPTX',
    'Display Limit Modal',
    'Display Limit Notification',
    'Limit Button',
    'Limit Modal Edu Button',
    'Limit Modal Pro Button',
    'Deck Created',
    'New Deck',
    'Land on Education Page',
    'View player page',
    'Editor Opened',
    'App Became Active',
    'signin',
    'Privacy',
    'Slide start',
    'Share',
    'Countdown Pro Button',
    'Display Video Editor Modal',
    'Display Zuru Upgrade Modal',
    'Download PPTX',
    'Downloaded Video',
    'Ended Onboarding',
    'Land on Classroom Page',
    'Land on Homepage',
    'Land on Realtor Page',
    'Land on Zuru Page',
    'Recorded Audio',
    'Set Privacy Public',
    'Set Privacy Restricted',
    'Sign In',
    'Start',
    'Started Onboarding',
    'Zuru Upgrade Edu Button',
    'Zuru Upgrade Pro Button',
]

CHURN = [
    # "account_age",
    # "camp_deliveries",
    "signin_ratio",
    "Slide start",
    "vertical_educator",
    "Editor Opened",
    "Deck Created",
    "vertical_marketing",
    "Started Onboarding",
    "Export",
    "signin",
    "App Became Active",
    "Sign In",
    "View player page",
    "Land on Pricing Page",
    "Share",
    "Ended Onboarding",
    "Display Video Editor Modal",
    "Export PPTX",
    "Recorded Audio",
    "Land on Classroom Page",
    "vertical_real_estate",
    "Export PPT",
    "vertical_student",
    "Display Limit Notification",
    "Land on Zuru Page",
    "Start",
    "Land on Education Page",
    "Set Privacy Restricted",
    "Display Welcome Countdown",
    "Privacy",
    "vertical_coach",
    "vertical_health",
    "vertical_non-profit",
    "vertical_religious_organization",
    "vertical_professional",
    "Land on Checkout Page",
    "Click Button",
    "Downloaded Video",
    "Successfully completed edu signup",
    "Set Privacy Public",
    "vertical_sales",
    "Validation failed",
    "signup",
    "New Deck",
    "vertical_small_business_owner",
    "upgrade",
    "vertical_other",
    "Download PPTX",
    "Successfully completed pro signup",
    "Display Limit Modal",
    "Error on payment",
    "Limit Button",
    "Sign Up",
    "Successfully completed classroom upgrade",
    "Successfully completed edu upgrade",
    "Successfully completed pro upgrade",
    "vertical_hr",
    "vertical_lawyer",
]
